# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Acorn < Formula
  desc "Acorn CLI"
  homepage "https://acorn.io"
  version "0.7.1"
  license "Apache 2.0"

  on_macos do
    url "https://github.com/acorn-io/acorn/releases/download/v0.7.1/acorn-v0.7.1-macOS-universal.tar.gz"
    sha256 "d4448ce19df17dcdf67b2122fa11397ddc9315fc88659e4043019595cb0420c2"

    def install
      bin.install "acorn"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/acorn-io/acorn/releases/download/v0.7.1/acorn-v0.7.1-linux-arm64.tar.gz"
      sha256 "89eed16c4c9f3d214387056ea44d52fdb24cb7643547623fe89e9384ff6a6dcf"

      def install
        bin.install "acorn"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/acorn-io/acorn/releases/download/v0.7.1/acorn-v0.7.1-linux-amd64.tar.gz"
      sha256 "552ad9afbda93eb6fd6c3dfdc3d1ca1c559a5994e844971aa0965e394ba526df"

      def install
        bin.install "acorn"
      end
    end
  end
end
